#!/usr/bin/env python3
"""Derive the machine-readable rule set and the rule index from rules/*.md.

`rules/*.md` is the source of truth and is hand-authored. Everything under
`generated/` is derived and committed, so a harness with no python interpreter
still gets it. `--check` regenerates in memory and fails if the tree drifted.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RULES_DIR = ROOT / "rules"
OUT_DIR = ROOT / "generated"

DEF_RE = re.compile(r"^\*\*(AKW-\d{2}\.\d+)\*\*[ \t]*(.*)$")
FENCE_RE = re.compile(r"^\s*(?:```|~~~)")
ID_RE = re.compile(r"AKW-\d{2}\.\d+")
CHECK_RE = re.compile(r"^- \[ \] (.+?)\s*\(([^)]*AKW-\d{2}\.\d+[^)]*)\)\s*$")
SECTION_RE = re.compile(r"^##\s+(.+?)\s*$")
ARCHIVE_RE = re.compile(r"^###\s+(AKW-\d{2}\.\d+)\s*·\s*(.+?)\s*$")
EXCLUDED_RE = re.compile(r"^\|\s*(AKW-\d{2}\.\d+)\s*\|\s*(.+?)\s*\|\s*$")
HEADING_RE = re.compile(r"^#{1,4}\s")

CONFORMANCE = "70-conformance.md"
ARCHIVE = "90-archive.md"

# Which rule areas are written into generated/standard.md. Everything else is
# routed: the checklist names the owning file, and the skill reads it only when
# a row applies. Retune here and regenerate; nothing else encodes the split.
CARRY_AREAS = ("20", "30", "40", "50")
ROUTED_AREAS = ("00", "10", "60", "90")

NOTE = (
    "<!-- Generated by rules/scripts/generate.py. Edit rules/*.md, not this file. -->"
)


def logical_lines(text: str) -> list[str]:
    """Join continuation lines so a wrapped check reads as one line."""
    out: list[str] = []
    for raw in text.splitlines():
        if raw[:1] in (" ", "\t") and raw.strip() and not raw.lstrip().startswith("- "):
            if out:
                out[-1] = f"{out[-1].rstrip()} {raw.strip()}"
                continue
        out.append(raw)
    return out


def strip_fences(lines: list[str]) -> list[bool]:
    """Flag each line as inside-code so a fenced example is never a definition."""
    inside = []
    depth = 0
    for line in lines:
        if FENCE_RE.match(line):
            inside.append(True)
            depth ^= 1
            continue
        inside.append(bool(depth))
    return inside


def first_sentence(body: str) -> str:
    flat = " ".join(body.split())
    # A period preceded by a capital ends an abbreviation (U.S.), not a sentence.
    cut = re.split(r"(?<![A-Z])[.:]\s", flat, maxsplit=1)[0].rstrip(":")
    return (cut[:117] + "...") if len(cut) > 120 else cut


def parse_rules() -> tuple[dict[str, dict], list[dict], list[dict], list[dict]]:
    rules: dict[str, dict] = {}
    checks: list[dict] = []
    archive: list[dict] = []
    excluded: list[dict] = []
    order = 0

    for path in sorted(RULES_DIR.glob("*.md")):
        rel = f"rules/{path.name}"
        text = path.read_text(encoding="utf-8")
        # A check line wraps; a rule body must keep its authored line breaks.
        lines = logical_lines(text) if path.name == CONFORMANCE else text.splitlines()
        fenced = strip_fences(lines)

        section = ""
        current: dict | None = None
        body: list[str] = []

        def flush() -> None:
            if current is not None:
                text = "\n".join(body).strip("\n")
                current["body"] = text
                current["title"] = first_sentence(text)
                rules[current["id"]] = current

        for i, line in enumerate(lines):
            if fenced[i]:
                body.append(line)
                continue
            hit = SECTION_RE.match(line)
            if hit:
                flush()
                current, body = None, []
                section = hit.group(1)
                continue
            if path.name == CONFORMANCE:
                if section.startswith("Out of scope"):
                    hit = EXCLUDED_RE.match(line)
                    if hit:
                        excluded.append({"id": hit.group(1), "why": hit.group(2)})
                    continue
                hit = CHECK_RE.match(line)
                if hit:
                    order += 1
                    checks.append(
                        {
                            "order": order,
                            "section": section,
                            "text": hit.group(1).strip(),
                            "ids": ID_RE.findall(hit.group(2)),
                        }
                    )
                continue
            if path.name == ARCHIVE:
                hit = ARCHIVE_RE.match(line)
                if hit:
                    archive.append({"id": hit.group(1), "disposition": hit.group(2)})
                continue
            hit = DEF_RE.match(line)
            if hit:
                flush()
                current = {
                    "id": hit.group(1),
                    "area": hit.group(1).split(".")[0].split("-")[1],
                    "section": section,
                    "source": rel,
                }
                body = [hit.group(2)]
                continue
            if current is not None:
                if HEADING_RE.match(line):
                    flush()
                    current, body = None, []
                    continue
                body.append(line)

        flush()

    by_id: dict[str, dict] = {}
    for check in checks:
        for rid in check["ids"]:
            by_id.setdefault(rid, check)
    for rule in rules.values():
        check = by_id.get(rule["id"])
        rule["check"] = (
            {"order": check["order"], "section": check["section"], "text": check["text"]}
            if check
            else None
        )
    return rules, checks, archive, excluded


def checklist_table(checks: list[dict], rules: dict[str, dict], carried_col: bool) -> list[str]:
    """The checklist. `carried_col` marks rows whose rule text is in this file."""
    out: list[str] = []
    section = None
    for check in checks:
        if check["section"] != section:
            section = check["section"]
            out += ["", f"### {section}", ""]
            out += (
                ["| Check | ID | Source |", "|---|---|---|"]
                if carried_col
                else ["| Check | ID | Source |", "|---|---|---|"]
            )
        for rid in check["ids"]:
            rule = rules.get(rid)
            if not carried_col:
                out.append(f"| {check['text']} | {rid} | `{rule['source'] if rule else '**undefined**'}` |")
            elif rule and rule["area"] in CARRY_AREAS:
                out.append(f"| {check['text']} | {rid} | carried below |")
            else:
                out.append(f"| {check['text']} | {rid} | `{rule['source'] if rule else '**undefined**'}` |")
    return out


def render_index(checks, rules, archive, gaps) -> str:
    out: list[str] = [NOTE, "", "# AKW-100 · Rule Index", ""]
    out += [
        "Every rule ID the standard defines, in checklist order. `Source` is the",
        "file that owns the rule; read it when the Check column applies.",
    ]
    out += checklist_table(checks, rules, carried_col=False)
    if gaps["unchecked"]:
        out += ["", "## Defined but not checked", ""]
        out += ["| ID | Rule | Source |", "|---|---|---|"]
        for rid in gaps["unchecked"]:
            rule = rules[rid]
            out.append(f"| {rid} | {rule['title']} | `{rule['source']}` |")
    if gaps["excluded"]:
        out += ["", "## Out of scope for a note check", ""]
        out += ["| ID | Why | Source |", "|---|---|---|"]
        for entry in gaps["excluded"]:
            rule = rules.get(entry["id"])
            src = f"`{rule['source']}`" if rule else "**undefined**"
            out.append(f"| {entry['id']} | {entry['why']} | {src} |")
    if archive:
        out += ["", "## Archive", "", "| ID | Disposition |", "|---|---|"]
        out += [f"| {a['id']} | {a['disposition']} |" for a in archive]
    out += [
        "",
        f"<!-- coverage: {len(checks)} checks, {len(rules)} rules, "
        f"{len(gaps['unchecked'])} unchecked, {len(gaps['excluded'])} excluded, "
        f"{len(gaps['dangling'])} dangling -->",
        "",
    ]
    return "\n".join(out)


def render_standard(checks, rules, ordered, gaps) -> str:
    out: list[str] = [NOTE, "", "# AKW-100 · Standard", ""]
    out += [
        "The always-read part of the standard. Every rule below applies to any",
        "Keynote. Read this file before drafting; do not work from memory.",
        "",
        "A checklist row marked `carried below` needs no other file. A row naming a",
        "file does: read that file when the row applies to the Keynote in hand.",
    ]
    out += ["", "## Checklist"]
    out += checklist_table(checks, rules, carried_col=True)

    out += ["", "## The rules"]
    carried = [r for r in ordered if r["area"] in CARRY_AREAS]
    source = None
    for rule in carried:
        if rule["source"] != source:
            source = rule["source"]
            out += ["", f"### {source}", ""]
        else:
            out.append("")
        # body holds the text after the bold ID; the ID must survive in this file.
        out.append(f"**{rule['id']}** {rule['body']}")

    routed_unchecked = [
        rid for rid in gaps["unchecked"] if rules[rid]["area"] in ROUTED_AREAS
    ]
    if routed_unchecked:
        out += ["", "## Routed rules with no checklist row", ""]
        out += ["| ID | Rule | Source |", "|---|---|---|"]
        for rid in routed_unchecked:
            rule = rules[rid]
            out.append(f"| {rid} | {rule['title']} | `{rule['source']}` |")

    out += ["", "## Routed files", ""]
    out += ["| File | Rules |", "|---|---|"]
    for area in ROUTED_AREAS:
        group = [r for r in ordered if r["area"] == area]
        if group:
            out.append(f"| `{group[0]['source']}` | {len(group)} |")
    out += [""]
    return "\n".join(out)


def build() -> tuple[dict[str, str], dict]:
    rules, checks, archive, excluded = parse_rules()
    ordered = sorted(rules.values(), key=lambda r: (r["area"], int(r["id"].split(".")[1])))
    checked = {rid for c in checks for rid in c["ids"]}
    excluded_ids = {e["id"] for e in excluded}
    gaps = {
        "unchecked": [
            r["id"]
            for r in ordered
            if r["id"] not in checked and r["id"] not in excluded_ids
        ],
        "dangling": sorted(checked - set(rules)),
        "excluded": excluded,
        "excluded_but_checked": sorted(excluded_ids & checked),
        "excluded_but_undefined": sorted(excluded_ids - set(rules)),
    }

    payload = {
        "standard": "AKW-100",
        "generated_from": sorted(f"rules/{p.name}" for p in RULES_DIR.glob("*.md")),
        "carry_areas": list(CARRY_AREAS),
        "checks": checks,
        "rules": ordered,
        "archive": archive,
        "excluded": excluded,
        "gaps": gaps,
    }

    return (
        {
            "generated/rules.json": json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
            "generated/index.md": render_index(checks, rules, archive, gaps),
            "generated/standard.md": render_standard(checks, rules, ordered, gaps),
        },
        gaps,
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if generated output is stale")
    ap.add_argument(
        "--strict", action="store_true", help="also fail when a rule has no checklist row"
    )
    args = ap.parse_args()

    artifacts, gaps = build()

    errors: list[str] = []
    if args.strict and gaps["unchecked"]:
        errors.append(
            f"{len(gaps['unchecked'])} rule(s) with no checklist row: "
            f"{', '.join(gaps['unchecked'])}"
        )
    if gaps["dangling"]:
        errors.append(f"checklist cites undefined rules: {', '.join(gaps['dangling'])}")
    if gaps["excluded_but_checked"]:
        errors.append(f"excluded and checked at once: {', '.join(gaps['excluded_but_checked'])}")
    if gaps["excluded_but_undefined"]:
        errors.append(f"excluded rules that do not exist: {', '.join(gaps['excluded_but_undefined'])}")

    stale: list[str] = []
    for rel, content in artifacts.items():
        path = ROOT / rel
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    for message in errors:
        print(f"error: {message}", file=sys.stderr)

    if args.check:
        for rel in stale:
            print(f"stale: {rel}", file=sys.stderr)
        if stale:
            print("run: just rules generate", file=sys.stderr)
        if stale or errors:
            return 1
        print("generated output is current")
        return 0

    for rel in artifacts:
        print(f"wrote {rel}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
